# Describes the format for available component services
process:
  name: Process
  description: 执行文本命令
  fields:
    text:
      name: Text
      description: 执行命令
      example: 打开所有灯
      selector:
        text: