# Describes the format for available component services
process:
  description: Launch a conversation from a transcribed text.
  fields:
    text:
      description: Transcribed text
      example: Turn all lights on
reload:
  description: 重新加载 intent_script 配置
setting:
  description: 设置相关配置
  fields:
    media_player:
      description: 视频播放器（电视投屏要用）
      example: media_player.android_tv
    user_id:
      description: 小米账号加密ID（过滤其它人接入时需要）
    open_mic:
      description: 语音结束后是否继续开麦
      example: false