blueprint:
  name: 小度音箱电视频道
  description: 网络电视资源IPTV
  domain: automation
  source_url: https://github.com/shaonianzhentan/conversation
  input:
    media_entity:
      name: 视频播放器
      description: 投屏播放的播放器实体
      default: []
      selector:
        target:
          entity:
            domain: media_player
trigger:
- platform: event
  event_type: xiaodu_event
  event_data:
    type: SetTVChannelRequest
    domain: media_player
action:
- service: media_player.play_media
  data:
    media_content_type: video
    media_content_id: >
      {% set type = trigger.event.data.deltaValue.upper() %}
      {%- if type == "CCTV1" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv1/HD-8000k-1080P-cctv1
      {%- elif type == "CCTV2" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv2/HD-8000k-1080P-cctv2
      {%- elif type == "CCTV3" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv3/HD-8000k-1080P-cctv3
      {%- elif type == "CCTV4" -%}
        http://183.207.248.71:80/cntv/live1/cctv-4/cctv-4
      {%- elif type == "CCTV5" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv5/HD-8000k-1080P-cctv5
      {%- elif type == "CCTV6" -%}
        http://183.207.248.71:80/cntv/live1/cctv-6/cctv-6
      {%- elif type == "CCTV7" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv7/HD-8000k-1080P-cctv7
      {%- elif type == "CCTV8" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv8/HD-8000k-1080P-cctv8
      {%- elif type == "CCTV9" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv9/HD-8000k-1080P-cctv9
      {%- elif type == "CCTV10" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv10/HD-8000k-1080P-cctv10
      {%- elif type == "CCTV11" -%}
        http://183.207.248.71:80/cntv/live1/n-cctv-11/n-cctv-11
      {%- elif type == "CCTV12" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv12/HD-8000k-1080P-cctv12
      {%- elif type == "CCTV13" -%}
        http://183.207.248.71:80/cntv/live1/cctv-13/cctv-13
      {%- elif type == "CCTV14" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv14/HD-8000k-1080P-cctv14
      {%- elif type == "CCTV15" -%}
        http://183.207.248.71:80/cntv/live1/n-cctv-15/n-cctv-15
      {%- elif type == "CCTV17" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-cctv17/HD-8000k-1080P-cctv17
      {%- elif type == "广东卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-guangdongstv/n-guangdongstv
      {%- elif type == "东南卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-dongnanstv/n-dongnanstv
      {%- elif type == "东方卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-dongfangstv/n-dongfangstv
      {%- elif type == "北京卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-2500k-1080P-beijingstv/HD-2500k-1080P-beijingstv
      {%- elif type == "北京纪实" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-beijingjishi/HD-8000k-1080P-beijingjishi
      {%- elif type == "南方卫视" -%}
        http://183.207.248.71:80/cntv/live1/SD-4000k-576P-nanfangstv/SD-4000k-576P-nanfangstv
      {%- elif type == "厦门卫视" -%}
        http://183.207.248.71:80/cntv/live1/SD-4000k-576P-xiamenstv/SD-4000k-576P-xiamenstv
      {%- elif type == "天津卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-2500k-1080P-tianjinstv/HD-2500k-1080P-tianjinstv
      {%- elif type == "安徽卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-anhuistv/HD-8000k-1080P-anhuistv
      {%- elif type == "山东卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-2500k-1080P-shandongstv/HD-2500k-1080P-shandongstv
      {%- elif type == "江苏卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-2500k-1080P-jiangsustv/HD-2500k-1080P-jiangsustv
      {%- elif type == "江西卫视" -%}
        http://183.207.248.71:80/cntv/live1/jiangxistv/jiangxistv
      {%- elif type == "河北卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-hebeistv/n-hebeistv
      {%- elif type == "浙江卫视" -%}
        http://183.207.248.71:80/cntv/live1/zhejiangstv/zhejiangstv
      {%- elif type == "深圳卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-2500k-1080P-shenzhenstv/HD-2500k-1080P-shenzhenstv
      {%- elif type == "湖北卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-2500k-1080P-hubeistv/HD-2500k-1080P-hubeistv
      {%- elif type == "湖南卫视" -%}
        http://183.207.248.71:80/cntv/live1/hunanstv/hunanstv
      {%- elif type == "重庆卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-chongqingstv/HD-8000k-1080P-chongqingstv
      {%- elif type == "黑龙江卫视" -%}
        http://183.207.248.71:80/cntv/live1/HD-8000k-1080P-heilongjiangstv/HD-8000k-1080P-heilongjiangstv
      {%- elif type == "四川卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-sichuanstv/n-sichuanstv
      {%- elif type == "云南卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-yntv1/n-yntv1
      {%- elif type == "宁夏卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-ningxiastv/n-ningxiastv
      {%- elif type == "兵团卫视" -%}
        http://183.207.248.71:80/cntv/live1/SD-4000k-576P-bingtuanstv/SD-4000k-576P-bingtuanstv
      {%- elif type == "山西卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-shanxistv/n-shanxistv
      {%- elif type == "广西卫视" -%}
        http://183.207.248.71:80/cntv/live1/n-guangxistv/n-guangxistv
      {%- elif type == "卡酷少儿" -%}
        http://183.207.248.71:80/cntv/live1/n-kakukaton/n-kakukaton
      {%- elif type == "嘉佳卡通" -%}
        http://183.207.248.71:80/cntv/live1/SD-4000k-576P-jiajiakaton/SD-4000k-576P-jiajiakaton
      {%- elif type == "炫动卡通" -%}
        http://183.207.248.71:80/cntv/live1/n-xuandongkaton/n-xuandongkaton
      {%- elif type == "金鹰卡通" -%}
        http://183.207.248.71:80/cntv/live1/n-jinyingkaton/n-jinyingkaton
      {%- elif type == "优漫卡通" -%}
        http://183.207.248.71:80/cntv/live1/n-youmankaton/n-youmankaton
      {%- endif -%}
  target: !input media_entity